pipeline {
    agent any

    stages {

        stage('Install Conan Dependencies') {
            steps {
				sh 'cd ci-cd-test'
				sh 'ls'
                sh 'conan profile detect --force'
                sh 'conan install . --output-folder=build --build=missing'
            }
        }

        stage('Configure') {
            steps {
                sh 'cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=build/generators/conan_toolchain.cmake'
            }
        }

        stage('Build') {
            steps {
                sh 'cmake --build build'
            }
        }

        stage('Test') {
            steps {
                sh 'ctest --test-dir build'
            }
        }
    }
}